package io.github.dependencyanalysis.runtime;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/** Immutable version metadata generated by the Maven build. */
public final class BuildMetadata {

    /** Generated metadata resource. */
    private static final String RESOURCE =
            "/META-INF/dependency-analyzer-build.properties";

    /** Loaded build properties. */
    private static final Properties VALUES = load();

    private BuildMetadata() {
    }

    /** @return Analyzer release version */
    public static String getAnalyzerVersion() {
        return required("analyzer.version");
    }

    /** @return embedded Artifact Path Plugin release version */
    public static String getArtifactPathPluginVersion() {
        return required("artifact-path-plugin.version");
    }

    private static Properties load() {
        final Properties properties = new Properties();
        try (InputStream input = BuildMetadata.class
                .getResourceAsStream(RESOURCE)) {
            if (input == null) {
                throw new IllegalStateException(
                        "Build metadata resource is unavailable: "
                                + RESOURCE);
            }
            properties.load(input);
            return properties;
        } catch (IOException exception) {
            throw new IllegalStateException(
                    "Unable to read build metadata: " + RESOURCE,
                    exception);
        }
    }

    private static String required(final String key) {
        final String value = VALUES.getProperty(key, "").trim();
        if (value.isEmpty()) {
            throw new IllegalStateException(
                    "Build metadata property is unavailable: " + key);
        }
        return value;
    }
}
